package com.example.demo.Repository.Entities;
// default package
// Generated Mar 3, 2023, 8:43:28 PM by Hibernate Tools 6.2.0.CR1


import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * CreditCardsId generated by hbm2java
 */
@Embeddable
public class CreditCardsId  implements java.io.Serializable {


     private String number;
     private int usersId;

    public CreditCardsId() {
    }

    public CreditCardsId(String number, int usersId) {
       this.number = number;
       this.usersId = usersId;
    }
   


    @Column(name="number", nullable=false, length=60)
    public String getNumber() {
        return this.number;
    }
    
    public void setNumber(String number) {
        this.number = number;
    }


    @Column(name="users_id", nullable=false)
    public int getUsersId() {
        return this.usersId;
    }
    
    public void setUsersId(int usersId) {
        this.usersId = usersId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CreditCardsId) ) return false;
		 CreditCardsId castOther = ( CreditCardsId ) other; 
         
		 return ( (this.getNumber()==castOther.getNumber()) || ( this.getNumber()!=null && castOther.getNumber()!=null && this.getNumber().equals(castOther.getNumber()) ) )
 && (this.getUsersId()==castOther.getUsersId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNumber() == null ? 0 : this.getNumber().hashCode() );
         result = 37 * result + this.getUsersId();
         return result;
   }   


}


