package com.example.demo.Repository.Entities;
// default package
// Generated Mar 3, 2023, 8:43:28 PM by Hibernate Tools 6.2.0.CR1


import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.sql.Timestamp;

/**
 * CreditCards generated by hbm2java
 */
@Entity
@Table(name="credit_cards"
    ,catalog="flamingoo"
)
public class CreditCards  implements java.io.Serializable {


     private CreditCardsId id;
     private User user;
     private Timestamp expireDate;
     private String cvv;
     private String holderName;

    public CreditCards() {
    }

    public CreditCards(CreditCardsId id, User user, Timestamp expireDate, String cvv, String holderName) {
       this.id = id;
       this.user = user;
       this.expireDate = expireDate;
       this.cvv = cvv;
       this.holderName = holderName;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="number", column=@Column(name="number", nullable=false, length=60) ), 
        @AttributeOverride(name="usersId", column=@Column(name="users_id", nullable=false) ) } )
    public CreditCardsId getId() {
        return this.id;
    }
    
    public void setId(CreditCardsId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="users_id", nullable=false, insertable=false, updatable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="expire_date", nullable=false, length=19)
    public Timestamp getExpireDate() {
        return this.expireDate;
    }
    
    public void setExpireDate(Timestamp expireDate) {
        this.expireDate = expireDate;
    }

    
    @Column(name="cvv", nullable=false, length=45)
    public String getCvv() {
        return this.cvv;
    }
    
    public void setCvv(String cvv) {
        this.cvv = cvv;
    }

    
    @Column(name="holder_name", nullable=false, length=45)
    public String getHolderName() {
        return this.holderName;
    }
    
    public void setHolderName(String holderName) {
        this.holderName = holderName;
    }




}


