package com.example.demo.Repository.Entities;
// default package
// Generated Mar 3, 2023, 8:43:28 PM by Hibernate Tools 6.2.0.CR1


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="flamingoo"
    , uniqueConstraints = @UniqueConstraint(columnNames="username") 
)
public class User  implements java.io.Serializable {


     private int id;
     private String username;
     private String password;
     private String firstName;
     private String lastName;
     private String gender;
     private String email;
     private String phone;
     private byte isAdmin;
     private String addressStreetName;
     private String addressCityName;
     private String addreessCountryName;
     private Set<CreditCards> creditCardses = new HashSet<CreditCards>(0);
     private Set<Product> products = new HashSet<Product>(0);
     private Set<OrderDetails> orderDetailses = new HashSet<OrderDetails>(0);

    public User() {
    }

	
    public User( String username, String password, String firstName,String lastNAme, String gender, String email, String phone, byte isAdmin) {
        this.username = username;
        this.password = password;
        this.firstName = firstName;
        this.lastName = lastNAme;

        this.gender = gender;
        this.email = email;
        this.phone = phone;
        this.isAdmin = isAdmin;
    }
    public User( String username, String password, String name, String gender, String email, String phone, byte isAdmin, String addressStreetName, String addressCityName, String addreessCountryName, Set<CreditCards> creditCardses, Set<Product> products, Set<OrderDetails> orderDetailses) {
       this.username = username;
       this.password = password;
       this.name = name;
       this.gender = gender;
       this.email = email;
       this.phone = phone;
       this.isAdmin = isAdmin;
       this.addressStreetName = addressStreetName;
       this.addressCityName = addressCityName;
       this.addreessCountryName = addreessCountryName;
       this.creditCardses = creditCardses;
       this.products = products;
       this.orderDetailses = orderDetailses;
    }
   
     @Id 

    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="username", unique=true, nullable=false, length=45)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false, length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="gender", nullable=false, length=45)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    
    @Column(name="email", nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="phone", nullable=false, length=45)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="isAdmin", nullable=false)
    public byte getIsAdmin() {
        return this.isAdmin;
    }
    
    public void setIsAdmin(byte isAdmin) {
        this.isAdmin = isAdmin;
    }

    
    @Column(name="address_street_name", length=45)
    public String getAddressStreetName() {
        return this.addressStreetName;
    }
    
    public void setAddressStreetName(String addressStreetName) {
        this.addressStreetName = addressStreetName;
    }

    
    @Column(name="address_city_name", length=45)
    public String getAddressCityName() {
        return this.addressCityName;
    }
    
    public void setAddressCityName(String addressCityName) {
        this.addressCityName = addressCityName;
    }

    
    @Column(name="addreess_country_name", length=45)
    public String getAddreessCountryName() {
        return this.addreessCountryName;
    }
    
    public void setAddreessCountryName(String addreessCountryName) {
        this.addreessCountryName = addreessCountryName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<CreditCards> getCreditCardses() {
        return this.creditCardses;
    }
    
    public void setCreditCardses(Set<CreditCards> creditCardses) {
        this.creditCardses = creditCardses;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="user_review_product", catalog="flamingoo", joinColumns = { 
        @JoinColumn(name="user_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="product_id", nullable=false, updatable=false) })
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<OrderDetails> getOrderDetailses() {
        return this.orderDetailses;
    }
    
    public void setOrderDetailses(Set<OrderDetails> orderDetailses) {
        this.orderDetailses = orderDetailses;
    }




}


